openapi: 3.2.1

info: 
  title: QRCode-Base-Attendance
  version: 1.0.0
  description: API for managing employees attendance records

server: 
  - url: http://localhost:3000/api/v1

tags: 
  - name: Employee
  - name: Attendance 

paths: 
  # Auth
  /auth/login:
    post:
      tags: 
        - Auth
      description: login user with username and password

      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
                - userName
                - password
              properties: 
                userName: 
                  type: string
                password: 
                  type: string
                
      response: 
        '200':
          description: User logged in
          conenet: 
            application/json:
              schema: 
                type: object
                properties: 
                  success: 
                    type: boolean
                  messag: 
                    type: string
                  user: 
                    type: object
                    properties: 
                      id: 
                        type: string
                        format: uuid
                      userName: 
                        type: string
        '400':
          description: Invalid username or passowrd
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  suceess: 
                    type: boolean
                message: 
                  type: string

      security: []
  
  /auth/logout:
    'post':
      tags: 
        - Auth
      description: Destroy user session and logout 

      responses: 
        '200':
          description: User logged out
          content:
            application/json:
              schema: 
                type: object
                propeties: 
                  success: 
                    type: boolean
                  message: 
                    type: string
        '401':
          $ref: '#/components/responses/unauthorized'
                
  /auth/update:
    'patch':
      tags:
        - Auth
      description: Update username and password
      
      requestBody:
        required: true
        content: 
          application/json:
            schema: 
              type: object
              required: 
                - userId
                - oldPassword
              properties: 
                userId:
                  type: string
                  format: uuid
                oldPassword: 
                  type: string
                newPassword:
                  type: string
                newUserName:
                  type: string
      responses: 
        '200':
          description: User updated
          content: 
            application/json:
              schema: 
                type: object
                properties: 
                  success:
                    type: boolean
                  message: 
                    type: string
                  user: 
                    type: object
                    properties: 
                      id: 
                        type: string
                      userName: 
                        type: string
        '404':
          $ref: '#/components/responses/notFound' 
        
        '401':
          $ref: '#/components/responses/unauthorized'

        '403':
          description: Invalid password
          content: 
            application/json:
              schema: 
                type: object
                properties:
                  success:  
                    type: boolean
                  message: 
                    type: string
                      


  # Employee


  # Attendance

components: 
  responses: 
    unauthorized: 
      description: Authetication is required
      content: 
        application/json:
          schema: 
            type: object
            properties: 
              success: 
                type: boolean
              message: 
                type: string
    
    notFound:
    description: User not found
    content: 
      application/json:
        schema: 
          type: object
          properties: 
            success:
              type: boolean
            message: 
              type: string